#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

PROG=/usr/bin/podkop-rotator.sh

start_service() {
    procd_open_instance
    # Передаем аргумент 'daemon', чтобы скрипт ушел в вечный цикл
    procd_set_param command "$PROG" daemon
    procd_set_param respawn
    procd_set_param file /etc/config/podkop_rotator
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}